### ISSUE TITLE
Missing hands

### ISSUE THREAD

**Issue by parasite12** [rux616/starfield-mantisorian-armor#2]
![IMG_7363](https://github.com/user-attachments/assets/bde2cfb9-8e2a-41c2-ba1b-f66a48552dad)
Love the mod but the hands went missing. It doesn’t affect any other spacesuit, it doesn’t affect my unarmored hands and uninstalling it doesn’t help.

**Comment by parasite12** [comment]
I managed to solve it by doing a hard restart of my Xbox

**Comment by rux616** [comment]
That's a weird issue. Thanks for letting me know you fixed it and how!
